USE [master]
GO

/****** Object:  Database [dev_IMP]    Script Date: 27-7-2020 22:21:19 ******/
CREATE DATABASE [dev_IMP]
 CONTAINMENT = NONE
 ON  PRIMARY
( NAME = N'dev_IMP', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dev_IMP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON
( NAME = N'dev_IMP_log', FILENAME = N'D:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\dev_IMP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [dev_IMP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [dev_IMP] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [dev_IMP] SET ANSI_NULLS OFF
GO

ALTER DATABASE [dev_IMP] SET ANSI_PADDING OFF
GO

ALTER DATABASE [dev_IMP] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [dev_IMP] SET ARITHABORT OFF
GO

ALTER DATABASE [dev_IMP] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [dev_IMP] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [dev_IMP] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [dev_IMP] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [dev_IMP] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [dev_IMP] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [dev_IMP] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [dev_IMP] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [dev_IMP] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [dev_IMP] SET  DISABLE_BROKER
GO

ALTER DATABASE [dev_IMP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [dev_IMP] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [dev_IMP] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [dev_IMP] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [dev_IMP] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [dev_IMP] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [dev_IMP] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [dev_IMP] SET RECOVERY FULL
GO

ALTER DATABASE [dev_IMP] SET  MULTI_USER
GO

ALTER DATABASE [dev_IMP] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [dev_IMP] SET DB_CHAINING OFF
GO

ALTER DATABASE [dev_IMP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF )
GO

ALTER DATABASE [dev_IMP] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO

ALTER DATABASE [dev_IMP] SET DELAYED_DURABILITY = DISABLED
GO

ALTER DATABASE [dev_IMP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [dev_IMP] SET  READ_WRITE
GO


